### ISSUE TITLE
.db file ?

### ISSUE THREAD

**Issue by flutter-painter** [tekartik/sembast_sqflite#4]
*sembast* already provides a .json file through exportDatabase(database).
Would *sembast_sqflite* provide a .db file ?
Client is more comfortable running SQL queries

**Comment by alextekartik** [comment]
Application should not assume any storage format as it could change (although it has not changed since the beginning yet).
While it is stored in a SQLite file (with a fixed schema) internal meta information is managed by sembast.

I added information its internal format here: https://github.com/tekartik/sembast_sqflite/blob/master/sembast_sqflite/doc/storage_format.md

**Comment by 926** [comment]
Thanks for making this clear. Will stick to original sembast then and will look for a JSON To SQL Converter.
